import { SK, CZ, SI, LT, EE, US, AT } from 'country-flag-icons/react/3x2';

export const constitutions = [
  {
    "krajina": "Slovensko",
    "znenie": "https://www.slov-lex.sk/ezbierky/pravne-predpisy/SK/ZZ/1992/460/",
    "zdroj: počet noviel": "https://sk.wikipedia.org/wiki/Ústava_Slovenskej_republiky_(1992)",
    "dátum prijatia": new Date(1992, 9, 1),
    "dĺžka (absolútna)": 16331,
    "počet novelizácií": 23,
    "zmena vyžaduje": "3/5 hlasov všetkých členov parlamentu",
    "zmena vyžaduje badge": "green",
    "icon": SK,
  },
  {
    "krajina": "Česká republika",
    "znenie": "https://www.psp.cz/docs/laws/constitution.html",
    "zdroj: počet noviel": "https://sk.wikipedia.org/wiki/%C3%9Astava_%C4%8Ceskej_republiky",
    "dátum prijatia": new Date(1992, 11, 16),
    "dĺžka (absolútna)": 5664,
    "počet novelizácií": 8,
    "zmena vyžaduje": "3/5 hlasov všetkých členov parlamentu + 3/5 prítomných členov senátu",
    "zmena vyžaduje badge": "orange",
    "icon": CZ,
  },
  {
    "krajina": "Slovinsko",
    "znenie": "https://www.us-rs.si/wp-content/uploads/2021/06/URS_angl_2021.pdf",
    "zdroj: počet noviel": "https://www.dz-rs.si/wps/portal/en/Home/AboutNA/PoliticalSystem/Constitution/!ut/p/z1/04_Sj9CPykssy0xPLMnMz0vMAfIjo8zivSy9Hb283Q0N3E3dLQwCQ7z9g7w8nNxDnUz0w8EKDHAARwP9KGL041EQhd94L_2o9Jz8JIhTHfOSjC3S9aOKUtNSi1KL9EqLgMIZJSUFxVaqBqoG5eXleun5-ek5qXrJ-bmqBti0ZOQXl-hHoKrUL8gNjajySQ0HAOpsxSw!/dz/d5/L2dBISEvZ0FBIS9nQSEh/",
    "dátum prijatia": new Date(1991, 11, 23),
    "dĺžka (absolútna)": 11718,
    "počet novelizácií": 11,
    "zmena vyžaduje": "2/3 hlasov všetkých členov národného zhromaždenia + ak 1/3 členov vyžiada, tak aj referendum",
    "zmena vyžaduje badge": "orange",
    "icon": SI,
  },
  {
    "krajina": "Litva",
    "znenie": "https://www.lrs.lt/sip/getFile?guid=e890662e-e777-4e45-b9e7-45dc26fb4bd0",
    "zdroj: počet noviel": "https://www.vle.lt/straipsnis/lietuvos-respublikos-konstitucija/",
    "dátum prijatia": new Date(1992, 9, 25),
    "dĺžka (absolútna)": 9422,
    "počet novelizácií": 13,
    "zmena vyžaduje": "2/3 v dvoch hlasovaniach s odstupom 3 mesiace",
    "zmena vyžaduje badge": "orange",
    "icon": LT,
  },
  {
    "krajina": "Estónsko",
    "znenie": "https://www.riigiteataja.ee/akt/115052015002",
    "zdroj: počet noviel": "https://www.riigiteataja.ee/akt/115052015002",
    "dátum prijatia": new Date(1992, 5, 28),
    "dĺžka (absolútna)": 6879,
    "počet novelizácií": 6, // 5+1 (nadobudne zmenu v 2026)
    "zmena vyžaduje": "Urgentne: 4/5 prvého parlamentu, inak 3/5 v dvoch hlasovaniach následného parlamentu, 1x stačí nadpolovičnú väčšinu",
    "zmena vyžaduje badge": "red",
    "icon": EE,
  },
  {
    "krajina": "USA",
    "znenie": "https://constitutioncenter.org/media/files/constitution.pdf",
    "zdroj: počet noviel": "https://www.constitutionfacts.com/us-constitution-amendments/fascinating-facts/",
    "dátum prijatia": new Date(1787, 9, 17),
    "dĺžka (absolútna)": 7591,
    "počet novelizácií": 27,
    "zmena vyžaduje": "2/3 hlasov všetkých členov hornej a dolnej komory parlamentu + schválenie 3/4 všetkých štátov federácie",
    "zmena vyžaduje badge": "red",
    "icon": US,
  },
  // {
  //   "krajina": "Rakúsko",
  //   "znenie": "https://www.konvent.gv.at/imfname_035687.pdf",
  //   "zdroj: počet noviel": "https://www.konvent.gv.at/imfname_035687.pdf",
  //   "dátum prijatia": new Date(1920, 9, 1),
  //   "dĺžka (absolútna)": 33792,
  //   "počet novelizácií": 100,
  //   "zmena vyžaduje": "2/3 prítomných v národnej rade (min polovica). Ak ide o základný princíp, musí byť aj referendum. Ak sa dotýka zmena spolkových krajín, musí navyše 2/3 spolkového snemu.",
  // },
];